"""PDF to DOCX conversion helpers exposed through the IntelliPDF tools namespace."""

from __future__ import annotations

from .converter import (
    ConversionMetadata,
    ConversionOptions,
    ConversionResult,
    PdfToDocxConverter,
    convert_pdf_to_docx,
)
from .ir import (
    Annotation,
    Comment,
    Document,
    DocumentMetadata,
    Endnote,
    Footnote,
    Numbering,
    OutlineItem,
    Paragraph,
    Picture,
    Run,
    Section,
    Shape,
    Table,
    TableCell,
    TableRow,
)
from .primitives import (
    BoundingBox,
    FormField,
    Image,
    Line,
    OutlineNode,
    Page,
    Path,
    PdfAnnotation,
    PdfDocument,
    TextBlock,
)

__all__ = [
    "ConversionMetadata",
    "ConversionOptions",
    "ConversionResult",
    "PdfToDocxConverter",
    "convert_pdf_to_docx",
    "Annotation",
    "Comment",
    "Document",
    "DocumentMetadata",
    "Endnote",
    "Footnote",
    "Numbering",
    "OutlineItem",
    "Paragraph",
    "Picture",
    "Run",
    "Section",
    "Shape",
    "Table",
    "TableCell",
    "TableRow",
    "BoundingBox",
    "FormField",
    "Image",
    "Line",
    "OutlineNode",
    "Page",
    "PdfAnnotation",
    "PdfDocument",
    "Path",
    "TextBlock",
]
